//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadingSystem.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoadingSystemEntities : DbContext
    {
        public LoadingSystemEntities()
            : base("name=LoadingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardLoadHistory> CardLoadHistories { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardTravelHistory> CardTravelHistories { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<StationPrice> StationPrices { get; set; }
    }
}
