//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadingSystem.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationPrice
    {
        public int StationPriceId { get; set; }
        public Nullable<int> StationOriginId { get; set; }
        public Nullable<int> StationDestinationId { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
